### PR TITLE
 Made the ingress annotations variable & fixed secret in the JAVA_OPTION_TOOLS

### PR DESCRIPTION
**Pull request by shazada**
See Comments in #30 , that one can be closed,  this is de new one. I couldn't cherry-pick the changes into the old pull request.

### CODE REVIEW

**Comment by shazada** [comment]
There are still some issues:

When I clone this chart chart:
and do an install with like:
cd charts/alfresco-search-services
helm upgrade --install search -f values.yaml -f values-local.yaml .

Everyting works fine!
Then I package this chart with helm package alfresco-search-servies

Then I create a new chart
```
version: 1.0.2
dependencies:
  - name: alfresco-search-service
    repository: oci://harbor.contezza.nl/alfresco-helm-charts
    version: 1.0.2-753eb3e
    condition: alfresco-search.enabled
```

Then it firstly complains about a backend port in the ingress, so I add this to the yaml file:

```
  service:
    externalPort: 80
```

So my new yaml file is then:
```
global:
  tracking:
    auth: secret
    sharedsecret: secret

alfresco-search-service:
  searchServicesImage:
    repository: alfresco/alfresco-search-services
    tag: 2.0.6
  ingress:
    enabled: true
    hostName: localhost
    basicAuth: YWRtaW46JGFwcjEkVVJqb29uS00kSEMuS1EwVkRScFpwSHB2a3JwTDd1Lg==
  resources:
    requests:
      memory: "1000Mi"
      cpu: "1000m"
    limits:
      memory: "4000Mi"
      cpu: "2000m"
  environment:
    SOLR_HEAP: "3g"
    SOLR_JAVA_MEM: "-Xms2g -Xmx3g"
  service:
    externalPort: 80
```

Then I get a non working ingress locally als on the Kubernetes cluster
image

So this piece of code is still probably not working:

```
    {{- if .Values.ingress.hostName }}
    host: {{ tpl .Values.ingress.hostName . }}
    {{- end }}
```

**Comment by alxgomz** [comment]
Hi @shazada ,
It sounds pretty strange you get this error with the packaged charts but not with the local sources.
Regarding the `externalPort` this is something I saw and addressed using the `$servicePort` instead of the value itself.
All other occurrence of this values are defaulted and I could not reproduce the issue.

I have done the following:
1. Create a master chart `cd /tmp && helm create mychart`
3. Checkout your branch in a different folder
4. Package the chart as-is `helm package . -d /tmp/mychart/charts/`
5. Add the following dependency to `/tmp/mychart/Chart.yaml`:
    ```yaml
    dependencies:                                                                                                                                       
       - name: alfresco-search-service                                                                                                                   
         version: 1.0.2                                                                                                                                  
```
6. Copy your example values file (without the `.service.externalPort` value) to `/tmp/mychart/more-values.yaml`
7. run helm template: `helm template /tmp/mychart -f more-values.yaml`

This gives me no error and the following ingress:

```yaml
---
# Source: mychart/charts/alfresco-search-service/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: release-name-alfresco-search-service-solr
  annotations:
    nginx.ingress.kubernetes.io/auth-secret: release-name-alfresco-search-service-ingress-secret
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-realm: Authentication Required - Alfresco Search
      Services
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/whitelist-source-range: 0.0.0.0/0

spec:
  rules:
  - http:
      paths:
      - path: /solr
        pathType: Prefix
        backend:
          service:
            name: release-name-alfresco-search-service-solr
            port:
              name: solr
    host: localhost
```

This sounds all good to me tbh. I'm wondering if you may have mised up version and you're not pulling the charts you think you are pulling.

At this point. I'm pretty confident moving forward with the PR and proceed to CI build/tests.
To do so we would however need you bump the `Chart.yaml` & `Chart.lock` files (otherwise CI will complain).
I would recommend using a pre-release like `1.0.3-alpha.1`

**Review by alxgomz — CHANGES_REQUESTED** [review]
To further proceed please bump the chart version to a pre-release so we can kick start tests

**Comment by shazada** [comment]
Sorry I was a off for a few days, I'll respond asap.

**Comment by shazada** [comment]
Wat do you mean by:


To further proceed please bump the chart version to a pre-release so we can kick start tests
?

**Comment by shazada** [comment]
And it's difficult for me to keep changing the chart if weeks go by, this chart is already in Acceptance at the customer and is now being reviewed by the customer. So I can't keep changing versions and try different charts. Hopefully we can just accept this version and if it also works on your side and then see if we can keep improving the chart.

**Comment by alxgomz** [comment]
> And it's difficult for me to keep changing the chart if weeks go by, this chart is already in Acceptance at the customer and is now being reviewed by the customer. So I can't keep changing versions and try different charts. Hopefully we can just accept this version and if it also works on your side and then see if we can keep improving the chart.

Yes, I understand. We've been you and I successively off for weeks which didn't help...
The problem at the moment is that there are conflicts between your branch and the main branch of our repo that needs resolving.
I your customer is currently reviewing this exact branch/code, maybe the best for this time would be for you to package and server the chart from this branch and serve it via your own chart registry for this version?
We can branch from `Contezza:Contezza/main` and open a new PR where we resolve conflicts and merge to release a `1.1.0-prerelease` so you `Contezza:Contezza/main` remains what your customer is reviewing?

**Comment by alxgomz** [comment]
Hi @shazada,

I was working on branching and resolving conflict and add tests. The tests actually showed the resulting ingress is kind of broken in case someone wants to setup another ingress type due to the type of values merging helm does:

```yaml
# Source: alfresco-search-service/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: release-name-alfresco-search-service-solr
  annotations:
    haproxy.org/auth-realm: My custom Realm requires auth
    haproxy.org/auth-secret: staging/solradmin
    haproxy.org/auth-type: basic-auth
    haproxy.org/whitelist: 192.168.0.0/24
    kubernetes.io/ingress.class: haproxy
    nginx.ingress.kubernetes.io/auth-realm: Authentication Required - Alfresco Search Services
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/whitelist-source-range: 0.0.0.0/0
```

Even though the nginx annotations are completely absent from the helm values passed at install time.

For that reason I have removed the ingressclass annotation from the value file as anything else but nginx id likely to work as expected at present time. Other nginx annotation can still be added to the values and should override as expected.
Pending PR here: https://github.com/Alfresco/alfresco-helm-charts/pull/52/files

**Comment by alxgomz** [comment]
superseeded by #52

**Pull request closed without merging**
